export const LOAD_FACEBOOK_SDK = 'LOAD_FACEBOOK_SDK';
export const LOAD_FACEBOOK_SDK_SUCCESS = "LOAD_FACEBOOK_SDK_SUCCESS";
export const LOAD_FACEBOOK_SDK_FAILURE = "LOAD_FACEBOOK_SDK_FAILURE";

export const FACEBOOK_LOGIN = "FACEBOOK_LOGIN";
export const FACEBOOK_LOGIN_SUCCESS = "FACEBOOK_LOGIN_SUCCESS";
export const FACEBOOK_LOGIN_FAILURE = "FACEBOOK_LOGIN_FAILURE";

export const LOAD_FACEBOOK_PROFILE = "LOAD_FACEBOOK_PROFILE";
export const LOAD_FACEBOOK_PROFILE_SUCCESS = "LOAD_FACEBOOK_PROFILE_SUCCESS";
export const LOAD_FACEBOOK_PROFILE_FAILURE = "LOAD_FACEBOOK_PROFILE_FAILURE";

export const LOAD_FACEBOOK_FRIENDS = "LOAD_FACEBOOK_FRIENDS";
export const LOAD_FACEBOOK_FRIENDS_SUCCESS = "LOAD_FACEBOOK_FRIENDS_SUCCESS";
export const LOAD_FACEBOOK_FRIENDS_FAILURE = "LOAD_FACEBOOK_FRIENDS_FAILURE";

export const LOAD_TREE_DATA = "LOAD_TREE_DATA";
export const LOAD_TREE_DATA_SUCCESS = "LOAD_TREE_DATA_SUCCESS";
export const LOAD_TREE_DATA_FAILURE = "LOAD_TREE_DATA_FAILURE";

export const SET_SELECTED_MEMBER = "SET_SELECTED_MEMBER";
export const ADD_CHILDREN = "ADD_CHILDREN";