export const LOAD_GOOGLE_SDK = 'LOAD_GOOGLE_SDK';
export const LOAD_GOOGLE_SDK_SUCCESS = "LOAD_GOOGLE_SDK_SUCCESS";
export const LOAD_GOOGLE_SDK_FAILURE = "LOAD_GOOGLE_SDK_FAILURE";

export const GOOGLE_LOGIN = "GOOGLE_LOGIN";
export const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
export const GOOGLE_LOGIN_FAILURE = "GOOGLE_LOGIN_FAILURE";

export const LOAD_GOOGLE_PROFILE = "LOAD_GOOGLE_PROFILE";
export const LOAD_GOOGLE_PROFILE_SUCCESS = "LOAD_GOOGLE_PROFILE_SUCCESS";
export const LOAD_GOOGLE_PROFILE_FAILURE = "LOAD_GOOGLE_PROFILE_FAILURE";

export const LOAD_GOOGLE_FRIENDS = "LOAD_GOOGLE_FRIENDS";
export const LOAD_GOOGLE_FRIENDS_SUCCESS = "LOAD_GOOGLE_FRIENDS_SUCCESS";
export const LOAD_GOOGLE_FRIENDS_FAILURE = "LOAD_GOOGLE_FRIENDS_FAILURE";

export const LOAD_GOOGLE_CONTACT_PHOTO = "LOAD_GOOGLE_CONTACT_PHOTO";
export const LOAD_GOOGLE_CONTACT_PHOTO_SUCCESS = "LOAD_GOOGLE_CONTACT_PHOTO_SUCCESS";
export const LOAD_GOOGLE_CONTACT_PHOTO_FAILURE = "LOAD_GOOGLE_CONTACT_PHOTO_FAILURE";

export const LOAD_TREE_DATA = "LOAD_TREE_DATA";
export const LOAD_TREE_DATA_SUCCESS = "LOAD_TREE_DATA_SUCCESS";
export const LOAD_TREE_DATA_FAILURE = "LOAD_TREE_DATA_FAILURE";
export const SAVE_TREE_DATA_ON_CHANGE = "SAVE_TREE_DATA_ON_CHANGE";

export const SET_SELECTED_MEMBER = "SET_SELECTED_MEMBER";
export const SET_SELECTED_NEW_MEMBER = "SET_SELECTED_NEW_MEMBER";
export const SET_SELECTED_MEMBERS_PARENT = "SET_SELECTED_MEMBERS_PARENT";

export const ADD_CHILDREN = "ADD_CHILDREN";
export const ADD_SPOUSE = "ADD_SPOUSE";
export const ADD_BROTHER = "ADD_BROTHER";
export const ADD_PARENT = "ADD_PARENT";
export const DELETE_MEMBER = "DELETE_MEMBER";